Adding Ability to export diagrams - Issue #55
joethei/obsidian-plantuml pull request #56
Opened 2024-02-10 20:26 UTC by blacktau

Adds to the right click menu the ability to export the image.
Includes a setting to be able to specify an output folder with the default being to export into the same folder as the markdown note.
Export format aligns with the type specified in the code block, plantuml: png, plantuml-svg: svg, plantuml-ascii: txt
Filenames are derived from the diagram title following the @startuml tag or the markdown note name combined with the current date and time

2024-02-13 09:21 UTC, joethei requested changes

2024-02-14 09:18 UTC, blacktau commented on src/settings.ts
> +                .setName("Diagram Export Path")
updated as requested

2024-02-14 09:18 UTC, blacktau commented on src/debouncedProcessors.ts
> +                const renderToBlob = (img: HTMLImageElement, errorMessage: string, handleBlob: (blob: Blob) => Promise<void>) => {
all inline functions extracted out to class level.

2024-02-14 09:18 UTC, blacktau commented on src/debouncedProcessors.ts
> +                                const getFilename = () => {
all inline functions extracted out to class level.

2024-02-14 09:19 UTC, blacktau commented on src/debouncedProcessors.ts
> +                                        return folderOrFile as TFile;
cast has been removed

2024-03-04 12:34 UTC, merged